[package]
name = "test-program"
version = "0.9.0"
edition = "2021"

[dependencies]
# todo: remove bitvec after we get done implementing our own
bitvec = "1.0.1"
huffman_coding_lib={path="../huffman-coding-lib"}
