name: c build

on:
  push:
    paths:
    - c/**
  pull_request:
    paths:
    - c/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Clean-Test-Build
      run: make clean test build
      working-directory: ./c
