name: cpp build

on:
  push:
    paths:
    - cpp/**
  pull_request:
    paths:
    - cpp/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Clean-Build
      run: make clean build
      working-directory: ./cpp
