# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: cpp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build-Lib
      run: cmake . && make clean && make config=release
      working-directory: ./c++
    - name: Build-Main
      run: (cd src ; g++ -o ../bin/huffman main.cpp -L../bin -lhuffman)
      working-directory: ./c++
