name: go build

on:
  push:
    paths:
    - go/**
  pull_request:
    paths:
    - go/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    - name: Test
      run: go test -v ./...
      working-directory: ./go
    - name: Build
      run: go build -v ./...
      working-directory: ./go
