name: testall

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Go setup
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    - name: Java setup
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: build
      run: ./build-all.sh
    - name: capture
      run: ./capture-all.sh
    - name: Run Python script
      run: python .testall/verify.py
